### PR TITLE
A few initial commits

### PR DESCRIPTION
**Pull request by Pieloaf**
1. Added the decompiled client source code for anyone to download and edit
2. Updated the README formatting and added a RESOURCES doc
3. Added the initial code used to bypass steam

### CODE REVIEW

**Comment by Pieloaf** [comment]
Oops, I didn't realise that all commits to my fork would get added to the PR, should have made a branch. So I guess its a lil more than just initial commits at this point.

1. added a section to the main readme regarding contributing
2. created a markdown formatted copy of the terms and abbreviations post from the

**Comment by eltaino1** [comment]
@Pieloaf I dont know how to merge your commits yet. Im still learning how to use this. Pls go ahead approve and merge your changes/commits. I will learn eventually how to merge commits but I dont see why we should wait

**Comment by Pieloaf** [comment]
No worries at all there's no rush, merge conflicts are messy at the start. It wasn't until I was dealing with them on a job everyday that I actually became comfortable with them. I'm actually going to be away from this for the next week, have a friend from Germany staying over so I may not get the chance to do it until after that, possibly will have time on Tuesday though.

**Comment by eltaino1** [comment]
Im so you have that experience 🙂
Thank you for letting me know. Im also taking some time off to be with
family. I may not be very active jan19-feb 1

**Review by eltaino1 — APPROVED** [review]

**Review by eltaino1 — APPROVED** [review]

**Review by eltaino1 — APPROVED** [review]

**Review by eltaino1 — APPROVED** [review]

**Review by eltaino1 — APPROVED** [review]

**Comment by eltaino1** [comment]
@Pieloaf i learned how to approve commits and approved your 6 initial commits. Theres a conflict with Readme.md. I still dont know how to resolve it.

**Comment by Pieloaf** [comment]
thanks a million for sorting that, I just resolved the conflict now so it should be able to merge without issue. Although, I'm getting a message saying I don't have permission to merge, but there should just be a button at the end of this thread that will allow you to merge it.

**Pull request merged**
